monolog:
    channels: ['audit', 'monitoring']
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: info
            formatter: monolog.formatter.json
            include_stacktraces: true
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        audit:
            type: stream
            path: '%kernel.logs_dir%/audit.log'
            level: info
            formatter: monolog.formatter.json
            channels: ['audit']
        monitoring:
            type: stream
            path: '%kernel.logs_dir%/monitoring.log'
            level: info
            formatter: monolog.formatter.json
            channels: ['monitoring']
        deprecation:
            type: stream
            channels: ['php']
            path: '%kernel.logs_dir%/%kernel.environment%.deprecations.log'
            level: warning
