<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMuVgZnM\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMuVgZnM/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerMuVgZnM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerMuVgZnM\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerMuVgZnM\srcApp_KernelProdContainer([
    'container.build_hash' => 'MuVgZnM',
    'container.build_id' => '193c3482',
    'container.build_time' => 1557282839,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMuVgZnM');
