doctrine:
    orm:
        auto_generate_proxy_classes: false
        metadata_cache_pool: doctrine.system_cache_pool
        query_cache_pool: doctrine.system_cache_pool
        result_cache_pool: doctrine.result_cache_pool

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
