app_root:
    path: /
    defaults:
        _controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirect'
        path: /accounts
        permanent: true

controllers:
    resource: ../src/Controller/
    type: attribute