<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX8mqoyP\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX8mqoyP/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX8mqoyP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX8mqoyP\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerX8mqoyP\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'X8mqoyP',
    'container.build_id' => '18defb68',
    'container.build_time' => 1556829185,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX8mqoyP');
